package.json, src/js/components/zoomable-image/index.js, src/js/praca/praca-atividade.ctrl.js, src/js/praca/praca-atividade.html, yarn.lock
Adicionando ao evento o local e uf.
Dropando magnifier pois ele foi descontinuado pelo próprio criador.
Adicionando link para a praça CEU nos eventos.
=> Feature evento

README.md, package.json, src/css/app.css, src/js/dashboard/dashboard.events.controller.js, src/js/praca/parceiros-components/detail.component.js, src/js/praca/parceiros-components/list.component.js, src/js/praca/praca-detail.controller.js, src/js/praca/praca-list.html
Atualização da documentação para usar com um container docker.
=> Atualizando documentacao para utilizar o front com um container docker.

src/js/dashboard/vinculacao/vinculo-dialog.tmpl.html
Altera o componente de visualização da imagem no Dialog de Vinculação de um Gestor.
=> [FIX] Altera Componente de Imagem no Dialog de Vinculação

src/js/agenda/evento.controller.js, src/js/dashboard/dashboard.events.controller.js, src/js/home/geoloc.controller.js, src/js/praca/grupogestor-components/membrogestor-list.dialog.ctrl.js, src/js/praca/praca-detail.controller.js, src/js/settings/settings.controller.js
De acordo com issue #6 foi efetuada correção da funcionalidade.
=> [FIX] Modal de visualização de Grupos Gestores e Documentos.

Dockerfile, docker-compose.yml
Incorporando ao projeto as funcionalidades docker e docker compose
=> Feat docker

src/css/app.css, src/js/components/praca/card.component.js, src/js/dashboard/events.tmpl.html, src/js/dashboard/gestor/detail.component.js, src/js/dashboard/users/user-card.component.js, src/js/dashboard/vinculacao/vinculo.tmpl.html, src/js/home/home.html, src/js/praca/event-dialog.tmpl.html
Foi feito alguns ajustes gerais de interface em algumas telas.
=> Ajustes de interface em algumas telas.

src/js/dashboard/users/user-detail-dialog.html, src/js/praca/atores-components/atores-dialog.tmpl.html, src/js/praca/atores-components/atores.controller.js, src/js/praca/event-dialog.tmpl.html, src/js/praca/galeria-upload.tmpl.html, src/js/praca/pracainfo-dialog.tmpl.html
=> Feat alfabeto

src/js/dashboard/users/user-detail-dialog.html, src/js/praca/event-dialog.tmpl.html, src/js/praca/galeria-upload.tmpl.html, src/js/praca/pracainfo-dialog.tmpl.html
Card #58 
Adicionado o botão fechar nas modais de praça com acesso admin, padronização de ditas modais e padronização dos cards dashboards-usuarios
=> Modais padroes x

src/css/app.css, src/js/agenda/agenda.config.js, src/js/dashboard/dashboard.events.controller.js, src/js/praca/event-dialog.tmpl.html, src/js/praca/praca-detail.html
Feature finalizada, ao confirmar, conforme aliamos, favor fazer o merge, e atualizar o jenkings. NÃO DELETAR a branch pois jogaremos ela em prod conforme formos nos aliando.
=> Feat eventos praca

src/css/materialize-custom.css
Alterando fonte das modais desabilitadas para melhor legibilidade do sistema.
=> co-authored:@g-adler

src/js/praca/praca-detail.controller.js
Adicionando o botão de enviar fotos ao hamburguer na página da praça.
=> Fix hamburguer

src/js/dashboard/dashboard.events.controller.js
Melhorando a apresentação dos números no calendario de eventos.
=> [UPDATE] Adicionando label Eventos ao calendario de eventos

src/js/praca/grupogestor-components/grupogestor.component.js, src/js/praca/grupogestor-components/grupogestor.dialog.ctrl.js, src/js/praca/grupogestor-components/membrogestor-list.dialog.tmpl.html, src/js/praca/praca-detail.controller.js, src/js/services/grupogestor.service.js
[FIX] Correção de permissão para o gestor da praça sobre o grupo gestor seguindo requisições detalhadas na issue #32
=> [MERGE] Fet issue32 ajustes grupo gestor

src/js/praca/praca-detail.html
Ao clicar na logo e-pracas o usuário é redirecionado para o header da página index. #85
=> [fix] Melhorando redirecionamento da logo epracas

src/js/praca/event.controller.js, src/js/praca/praca-atividade.ctrl.js
Inserindo lógica para decremento ao mostrar a data final de evento da praça e lógica para incremento da data final ao salvar no banco.
=> Fix issue 65

src/js/dashboard/dashboard.events.controller.js, src/js/praca/event.controller.js, src/js/praca/praca-atividade.ctrl.js
concentar bug no calendario de eventos. issue #65 .
=> Alteração da lógica

src/js/dashboard/dashboard.events.controller.js
Correção do bug da Area do Gestor MinC
=> [Fix] Area gestor minc agenda

src/js/dashboard/dashboard.events.controller.js
Fix da Agenda Gestor no ambiente de produção. issue #103
=> [FIX] Agenda Gestor MinC Corrigido

src/css/app.css, src/js/dashboard/dashboard.events.controller.js, src/js/praca/event-dialog.tmpl.html, src/js/praca/event.controller.js, src/js/praca/grupogestor-components/finaliza-grupogestor.dialog.tmpl.html, src/js/praca/grupogestor-components/grupogestor.component.js, src/js/praca/grupogestor-components/grupogestor.dialog.ctrl.js, src/js/praca/grupogestor-components/membrogestor-list.dialog.tmpl.html, src/js/praca/grupogestor-components/membrogestor.dialog.tmpl.html, src/js/praca/praca-atividade.ctrl.js, src/js/praca/praca-atividade.html, src/js/praca/praca-detail.controller.js, src/js/praca/praca-detail.html, src/js/services/atividade.service.js
Aplicando as issues listadas:
#95 , #63 , #88 , #93 , #94 , #91 , #96
=> Feature issu52 exclusao evento

src/css/app.css, src/js/praca/event-dialog.tmpl.html, src/js/praca/event.controller.js, src/js/praca/praca-atividade.html, src/js/praca/praca-detail.controller.js, src/js/praca/praca-detail.html
Features abordadas nesse Pull Request:
Issues #52 #92 #94 #111 #96
=> [MERGE] SPRINT 4

src/js/praca/event.controller.js
corrige a issue #52  :))
:zap:
=> [FIX] formulário agora aceita tipo que retorna do banco

src/js/praca/praca-detail.html
Update - botão burguer do detalhamento da praça teve removido o evento.
=> [UPDATE] Remoção do botão Evento do Burguer na template praça detalhada

src/js/praca/pracainfo-dialog.tmpl.html, src/js/praca/pracainfo.controller.js
Co-authored-by: pedro <pedrophilipe.ti@gmail.com>
=> [FIX] desabilitando edição de campos e selecionando uf

src/js/praca/praca-detail.html, src/js/praca/pracainfo.controller.js
Correção da lista de próximos eventos do mais recente registrados para os mais antigos por data.
=> Fix proximos eventos praca detail

src/js/praca/praca-atividade.ctrl.js, src/js/services/atividade.service.js
Co-authored-by: Izabela <cizabelacristina@gmail.com>
Corrige options de atividades
Closes #119
=> Correção de amostragem para usuarios logados e deslogados em atividades

src/js/praca/grupogestor-components/grupogestor.dialog.tmpl.html
- Ajusta o ngf-max-size para 20MB pra igualar ao back-end
- Adiciona mensagem de erro informando tamanho máximo do arquivo
Closes #152
=> Mostra mensagem de erro quando arquivo excede tamanho máximo

src/js/praca/grupogestor-components/grupogestor.dialog.ctrl.js, src/js/praca/praca-card.component.js, src/js/praca/rh-components/rh.dialog.ctrl.js, src/js/services/rh.service.js
Inicializa datas no formulário de:
- adição de um grupo gestor
- finalização de um grupo gestor
- adição/alteração de um membro dos recursos humanos
- exclusão de um membro dos recursos humanos
Closes #89
=> Inicializa datas nos forms de rh e grupo gestor

src/css/app.css, src/js/layout/header.html
Aviso de compatibilidade de navegador!
=> Fix compatibilidade

src/js/dashboard/vinculacao/vinculoinfo-dialog.tmpl.html, src/js/layout/header.html
FIX requisição aberta em citismart 53815.
Correção de redirecionamento na aquisição e visualização dos documento no dashboard de vinculação
=> Fix redirecionamento inicio issue 204

src/js/home/home.html
=> [UPDATE] Atualização de nome para Estações Cidadania - Cultura

.gitignore, src/css/app.css, src/js/dashboard/gestor/detail.component.js, src/js/dashboard/gestor/list.component.js
Correção de dimensionamento dos Cards da área Administrativa do sistema
=> Fix gestor card praça

src/js/dashboard/dashboard.events.controller.js, src/js/dashboard/gestor/detail.component.js, src/js/dashboard/vinculacao/vinculoinfo-dialog.tmpl.html, src/js/home/home.html, src/js/praca/grupogestor-components/grupogestor.dialog.tmpl.html, src/js/praca/praca-detail.controller.js, src/js/praca/praca-detail.html, src/js/praca/pracainfo-dialog.tmpl.html
Reverts culturagovbr/epracas-frontend#212
=> Revert "Develop Atualização"
